### ISSUE TITLE
Import hook to catch missing shared object error

### ISSUE THREAD

**Issue by bennuttall** [bennuttall/piwheels#117]
If we can create an import hook to catch the missing shared object error, we can show users a helpful error message, and probably link them to the project page to find out what they need to install.

Currently, after installing `python-opencv`:

```bash
pi@raspberrypi:~ $ python3 -c "import cv2"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/cv2/__init__.py", line 3, in <module>
    from .cv2 import *
ImportError: libcblas.so.3: cannot open shared object file: No such file or directory
```

Proposed:

```bash
pi@raspberrypi:~ $ python3 -c "import cv2"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/cv2/__init__.py", line 3, in <module>
    from .cv2 import *
ImportError: Missing dependencies. Please refer to https://www.piwheels.org/project/opencv-python to see how to resolve this issue.
```

*I see a tricky part here: how do we know `cv2` means `opencv-python`?*

Thinking further ahead, if we were able to provide this kind of information through an API, we could automatically report back what they need to do to fix the issue :smile:

**Comment by basak** [comment]
Some suggestions:

 * It's a little dangerous (IMHO) to assume that an ImportError really is a piwheels-related issue in all cases.
 * Consider providing a mapping from failed shared object file to the package that provides it using some mechanism. The mapping itself should be relatively trivial to generate (`apt-file` etc).
 * Now you don't have to know that `cv2` means `opencv-python`, only that `libcblas.so.3` can be fixed by installing the `opencv-python` package.
 * Then enhance, rather than replace, the original message, so that you aren't hiding the actual failure from users and developers who might find that part still relevant (eg. if it isn't a piwheels-related issue).

**Comment by bennuttall** [comment]
#205 would make this possible!
