### ISSUE TITLE
piw-master vulnerable to PyPI server error

### ISSUE THREAD

**Issue by bennuttall** [bennuttall/piwheels#42]
I noticed that `piw-master` running on the piwheels master Pi fell over at some point over Christmas, due to a 504 Gateway Timeout on pypi.python.org.

We should catch this `ProtocolError` exception and enter a retry loop rather than throwing a fatal error.

![screenshot from 2018-01-02 14-26-54](https://user-images.githubusercontent.com/1609725/34487141-ec7d511e-efca-11e7-8049-64b236d0c5f3.png)

**Comment by bennuttall** [comment]
I'm encountering a similar problem with an SSL error:

```python
Traceback (most recent call last):                                        
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner             
    self.run()                                                                      
  File "/usr/local/lib/python3.5/dist-packages/piwheels/master/cloud_gazer.py", line
 73, in run                                                                         
    super().run()                                                                   
  File "/usr/local/lib/python3.5/dist-packages/piwheels/master/tasks.py", line 174, 
in run                                                                              
    self.loop()                                                                     
  File "/usr/local/lib/python3.5/dist-packages/piwheels/master/cloud_gazer.py", line
 56, in loop                                                                        
    for package, version in self.pypi:                                              
  File "/usr/local/lib/python3.5/dist-packages/piwheels/master/pypi.py", line 100,
n __iter__                                                                          
    events = self._get_events()                                                     
  File "/usr/local/lib/python3.5/dist-packages/piwheels/master/pypi.py", line 85, in
 _get_events
    return self.client.changelog_since_serial(self.serial)
  File "/usr/lib/python3.5/xmlrpc/client.py", line 1092, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python3.5/xmlrpc/client.py", line 1432, in __request
    verbose=self.__verbose
  File "/usr/lib/python3.5/xmlrpc/client.py", line 1134, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python3.5/xmlrpc/client.py", line 1146, in single_request
    http_conn = self.send_request(host, handler, request_body, verbose)
  File "/usr/lib/python3.5/xmlrpc/client.py", line 1259, in send_request
    self.send_content(connection, request_body)
  File "/usr/lib/python3.5/xmlrpc/client.py", line 1289, in send_content
    connection.endheaders(request_body)
  File "/usr/lib/python3.5/http/client.py", line 1103, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/usr/lib/python3.5/http/client.py", line 877, in send
    self.connect()
  File "/usr/lib/python3.5/http/client.py", line 1261, in connect
    server_hostname=server_hostname)
  File "/usr/lib/python3.5/ssl.py", line 385, in wrap_socket
    _context=self)
  File "/usr/lib/python3.5/ssl.py", line 760, in __init__
    self.do_handshake()
  File "/usr/lib/python3.5/ssl.py", line 996, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib/python3.5/ssl.py", line 641, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error
```

**Comment by waveform80** [comment]
That's ... bizarre. Errno 0 is "success" so I'm not sure what it's whinging about. May have to dig into ssl.py *shudder* ...

**Comment by waveform80** [comment]
From [Python issue 10808](https://bugs.python.org/issue10808):

> > "This information" being no information, is that really all you can get out of OpenSSL?
> 
> Well the situation as the same as a system call which would return
> failure but leave errno 0 (except that OpenSSL has its own
> kind-of-errnos).
> OpenSSL's error reporting is unfortunately poorly if at all documented,
> and I don't know what to do here.

OpenSSL strikes again. *head-desk*.

So, the best we can do is basically catch every OSError, ignore it and retry later. I'll push this in a bit.
