### ISSUE TITLE
Broken numpy inside Docker

### ISSUE THREAD

**Issue by jasongwartz** [bennuttall/piwheels#51]
Hey Ben,

Curious if you or anyone else has been able to run piwheels builds inside Docker containers on a Pi. No luck here:
```
$ docker run --rm -it python:3.5 bash

root@8cabc40c29db:/# pip3 install numpy -i https://www.piwheels.hostedpi.com/simple
Collecting numpy
  Downloading https://www.piwheels.hostedpi.com/simple/numpy/numpy-1.14.0-cp35-cp35m-linux_armv7l.whl (6.3MB)
    100% |████████████████████████████████| 6.3MB 17kB/s
Installing collected packages: numpy
Successfully installed numpy-1.14.0

root@8cabc40c29db:/# python
iPython 3.5.5 (default, Feb 16 2018, 00:40:25)
[GCC 4.9.2] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/numpy/core/__init__.py", line 16, in <module>
    from . import multiarray
ImportError: cannot import name 'multiarray'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/site-packages/numpy/__init__.py", line 142, in <module>
    from . import add_newdocs
  File "/usr/local/lib/python3.5/site-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/usr/local/lib/python3.5/site-packages/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *
  File "/usr/local/lib/python3.5/site-packages/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "/usr/local/lib/python3.5/site-packages/numpy/core/__init__.py", line 26, in <module>
    raise ImportError(msg)
ImportError:
Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
If you're working with a numpy git repo, try `git clean -xdf` (removes all
files not under version control).  Otherwise reinstall numpy.

Original error was: cannot import name 'multiarray'
```

Cheers!

**Comment by bennuttall** [comment]
I'm not surprised it doesn't work. I assume Python is built against a different ABI, so they'll be incompatible. Do you have the same issue with Docker on Linux?

It'll work for pure Python wheels but not for packages like numpy which required building, as they need to match the Python ABI.

**Comment by jasongwartz** [comment]
Ah, yeah - that makes sense. I tried using the resin raspbian image as a base as well (https://hub.docker.com/r/resin/rpi-raspbian/), but that has the same issue.

No worries, I'll continue building from source for now!

**Comment by waveform80** [comment]
Hmmm, if the docker image is based on Rasbian (which resin appears to be) I'd be rather surprised if it had a different ABI. That also isn't the typical error message that numpy raises when the ABI is at fault (as in fpectl/no-fpectl builds). It looks more like it's simply failing to find something which would suggest to me that some paths are different (or the paths Python is looking under are different).

Might be worth taking a look at sys.path and the various .pth files under the docker installation (and where pip is installing stuff) to see whether it all makes sense?

**Comment by tjguk** [comment]
Can you start python with "python -v"? That will turn on verbose messaging for imports. Very useful for seeing how far it gets and where it's looking.

**Comment by jasongwartz** [comment]
```
$ docker run --rm -it resin/rpi-raspbian:stretch
# apt-get update && apt-get install python3 python3-pip

# python3 -v

import _frozen_importlib # frozen
import _imp # builtin
import sys # builtin
import '_warnings' # <class '_frozen_importlib.BuiltinImporter'>
import '_thread' # <class '_frozen_importlib.BuiltinImporter'>
import '_weakref' # <class '_frozen_importlib.BuiltinImporter'>
import '_frozen_importlib_external' # <class '_frozen_importlib.FrozenImporter'>
import '_io' # <class '_frozen_importlib.BuiltinImporter'>
import 'marshal' # <class '_frozen_importlib.BuiltinImporter'>
import 'posix' # <class '_frozen_importlib.BuiltinImporter'>
import _thread # previously loaded ('_thread')
import '_thread' # <class '_frozen_importlib.BuiltinImporter'>
import _weakref # previously loaded ('_weakref')
import '_weakref' # <class '_frozen_importlib.BuiltinImporter'>
# installing zipimport hook
import 'zipimport' # <class '_frozen_importlib.BuiltinImporter'>
# installed zipimport hook
# /usr/lib/python3.5/encodings/__pycache__/__init__.cpython-35.pyc matches /usr/lib/python3.5/encodings/__init__.py
# code object from '/usr/lib/python3.5/encodings/__pycache__/__init__.cpython-35.pyc'
# /usr/lib/python3.5/__pycache__/codecs.cpython-35.pyc matches /usr/lib/python3.5/codecs.py
# code object from '/usr/lib/python3.5/__pycache__/codecs.cpython-35.pyc'
import '_codecs' # <class '_frozen_importlib.BuiltinImporter'>
import 'codecs' # <_frozen_importlib_external.SourceFileLoader object at 0x769f19f0>
# /usr/lib/python3.5/encodings/__pycache__/aliases.cpython-35.pyc matches /usr/lib/python3.5/encodings/aliases.py
# code object from '/usr/lib/python3.5/encodings/__pycache__/aliases.cpython-35.pyc'
import 'encodings.aliases' # <_frozen_importlib_external.SourceFileLoader object at 0x76a05290>
import 'encodings' # <_frozen_importlib_external.SourceFileLoader object at 0x769f17d0>
# /usr/lib/python3.5/encodings/__pycache__/utf_8.cpython-35.pyc matches /usr/lib/python3.5/encodings/utf_8.py
# code object from '/usr/lib/python3.5/encodings/__pycache__/utf_8.cpython-35.pyc'
import 'encodings.utf_8' # <_frozen_importlib_external.SourceFileLoader object at 0x76a08c90>
import '_signal' # <class '_frozen_importlib.BuiltinImporter'>
# /usr/lib/python3.5/encodings/__pycache__/latin_1.cpython-35.pyc matches /usr/lib/python3.5/encodings/latin_1.py
# code object from '/usr/lib/python3.5/encodings/__pycache__/latin_1.cpython-35.pyc'
import 'encodings.latin_1' # <_frozen_importlib_external.SourceFileLoader object at 0x76a0c290>
# /usr/lib/python3.5/__pycache__/io.cpython-35.pyc matches /usr/lib/python3.5/io.py
# code object from '/usr/lib/python3.5/__pycache__/io.cpython-35.pyc'
# /usr/lib/python3.5/__pycache__/abc.cpython-35.pyc matches /usr/lib/python3.5/abc.py
# code object from '/usr/lib/python3.5/__pycache__/abc.cpython-35.pyc'
# /usr/lib/python3.5/__pycache__/_weakrefset.cpython-35.pyc matches /usr/lib/python3.5/_weakrefset.py
# code object from '/usr/lib/python3.5/__pycache__/_weakrefset.cpython-35.pyc'
import '_weakrefset' # <_frozen_importlib_external.SourceFileLoader object at 0x76a0c970>
import 'abc' # <_frozen_importlib_external.SourceFileLoader object at 0x76a0c4f0>
import 'io' # <_frozen_importlib_external.SourceFileLoader object at 0x76a0c370>
# /usr/lib/python3.5/__pycache__/site.cpython-35.pyc matches /usr/lib/python3.5/site.py
# code object from '/usr/lib/python3.5/__pycache__/site.cpython-35.pyc'
# /usr/lib/python3.5/__pycache__/os.cpython-35.pyc matches /usr/lib/python3.5/os.py
# code object from '/usr/lib/python3.5/__pycache__/os.cpython-35.pyc'
import 'errno' # <class '_frozen_importlib.BuiltinImporter'>
# /usr/lib/python3.5/__pycache__/stat.cpython-35.pyc matches /usr/lib/python3.5/stat.py
# code object from '/usr/lib/python3.5/__pycache__/stat.cpython-35.pyc'
import '_stat' # <class '_frozen_importlib.BuiltinImporter'>
import 'stat' # <_frozen_importlib_external.SourceFileLoader object at 0x76a28490>
# /usr/lib/python3.5/__pycache__/posixpath.cpython-35.pyc matches /usr/lib/python3.5/posixpath.py
# code object from '/usr/lib/python3.5/__pycache__/posixpath.cpython-35.pyc'
# /usr/lib/python3.5/__pycache__/genericpath.cpython-35.pyc matches /usr/lib/python3.5/genericpath.py
# code object from '/usr/lib/python3.5/__pycache__/genericpath.cpython-35.pyc'
import 'genericpath' # <_frozen_importlib_external.SourceFileLoader object at 0x76a2d350>
import 'posixpath' # <_frozen_importlib_external.SourceFileLoader object at 0x76a28850>
# /usr/lib/python3.5/__pycache__/_collections_abc.cpython-35.pyc matches /usr/lib/python3.5/_collections_abc.py
# code object from '/usr/lib/python3.5/__pycache__/_collections_abc.cpython-35.pyc'
import '_collections_abc' # <_frozen_importlib_external.SourceFileLoader object at 0x76a2d670>
import 'os' # <_frozen_importlib_external.SourceFileLoader object at 0x76a1e470>
# /usr/lib/python3.5/__pycache__/_sitebuiltins.cpython-35.pyc matches /usr/lib/python3.5/_sitebuiltins.py
# code object from '/usr/lib/python3.5/__pycache__/_sitebuiltins.cpython-35.pyc'
import '_sitebuiltins' # <_frozen_importlib_external.SourceFileLoader object at 0x76a1e630>
# /usr/lib/python3.5/__pycache__/sysconfig.cpython-35.pyc matches /usr/lib/python3.5/sysconfig.py
# code object from '/usr/lib/python3.5/__pycache__/sysconfig.cpython-35.pyc'
import 'sysconfig' # <_frozen_importlib_external.SourceFileLoader object at 0x769cd670>
# /usr/lib/python3.5/__pycache__/_sysconfigdata.cpython-35.pyc matches /usr/lib/python3.5/_sysconfigdata.py
# code object from '/usr/lib/python3.5/__pycache__/_sysconfigdata.cpython-35.pyc'
# /usr/lib/python3.5/plat-arm-linux-gnueabihf/__pycache__/_sysconfigdata_m.cpython-35.pyc matches /usr/lib/python3.5/plat-arm-linux-gnueabihf/_sysconfigdata_m.py
# code object from '/usr/lib/python3.5/plat-arm-linux-gnueabihf/__pycache__/_sysconfigdata_m.cpython-35.pyc'
import '_sysconfigdata_m' # <_frozen_importlib_external.SourceFileLoader object at 0x769d75f0>
import '_sysconfigdata' # <_frozen_importlib_external.SourceFileLoader object at 0x769d74b0>
# /usr/lib/python3.5/__pycache__/sitecustomize.cpython-35.pyc matches /usr/lib/python3.5/sitecustomize.py
# code object from '/usr/lib/python3.5/__pycache__/sitecustomize.cpython-35.pyc'
import 'sitecustomize' # <_frozen_importlib_external.SourceFileLoader object at 0x769d7fb0>
import 'site' # <_frozen_importlib_external.SourceFileLoader object at 0x76a128b0>
Python 3.5.3 (default, Jan 19 2017, 14:11:04)
[GCC 6.3.0 20170124] on linux
Type "help", "copyright", "credits" or "license" for more information.
# extension module 'readline' loaded from '/usr/lib/python3.5/lib-dynload/readline.cpython-35m-arm-linux-gnueabihf.so'
# extension module 'readline' executed from '/usr/lib/python3.5/lib-dynload/readline.cpython-35m-arm-linux-gnueabihf.so'
import 'readline' # <_frozen_importlib_external.ExtensionFileLoader object at 0x769e7290>
import 'atexit' # <class '_frozen_importlib.BuiltinImporter'>
# /usr/lib/python3.5/__pycache__/rlcompleter.cpython-35.pyc matches /usr/lib/python3.5/rlcompleter.py
# code object from '/usr/lib/python3.5/__pycache__/rlcompleter.cpython-35.pyc'
import 'rlcompleter' # <_frozen_importlib_external.SourceFileLoader object at 0x769e7330>
```

This is from a Raspberry Pi, but the resin image seems to work and produce roughly the same output on an x86 machine (a macbook pro, in my case).

**Comment by tjguk** [comment]
Thanks. I meant: ... and then try to import numpy

**Comment by jasongwartz** [comment]
haha alright, here's what it looks like:

```
>>> import numpy
# /usr/local/lib/python3.5/dist-packages/numpy/__pycache__/__init__.cpython-35.pyc matches /usr/local/lib/python3.5/dist-packages/numpy/__init__.py
# code object from '/usr/local/lib/python3.5/dist-packages/numpy/__pycache__/__init__.cpython-35.pyc'
# /usr/lib/python3.5/__pycache__/__future__.cpython-35.pyc matches /usr/lib/python3.5/__future__.py
# code object from '/usr/lib/python3.5/__pycache__/__future__.cpython-35.pyc'
import '__future__' # <_frozen_importlib_external.SourceFileLoader object at 0xf62b5c30>
# /usr/lib/python3.5/__pycache__/warnings.cpython-35.pyc matches /usr/lib/python3.5/warnings.py
# code object from '/usr/lib/python3.5/__pycache__/warnings.cpython-35.pyc'
import 'warnings' # <_frozen_importlib_external.SourceFileLoader object at 0xf62b5ef0>
# /usr/local/lib/python3.5/dist-packages/numpy/__pycache__/_globals.cpython-35.pyc matches /usr/local/lib/python3.5/dist-packages/numpy/_globals.py
# code object from '/usr/local/lib/python3.5/dist-packages/numpy/__pycache__/_globals.cpython-35.pyc'
import 'numpy._globals' # <_frozen_importlib_external.SourceFileLoader object at 0xf62bc4f0>
# /usr/local/lib/python3.5/dist-packages/numpy/__pycache__/__config__.cpython-35.pyc matches /usr/local/lib/python3.5/dist-packages/numpy/__config__.py
# code object from '/usr/local/lib/python3.5/dist-packages/numpy/__pycache__/__config__.cpython-35.pyc'
import 'numpy.__config__' # <_frozen_importlib_external.SourceFileLoader object at 0xf62bc5d0>
# /usr/local/lib/python3.5/dist-packages/numpy/__pycache__/version.cpython-35.pyc matches /usr/local/lib/python3.5/dist-packages/numpy/version.py
# code object from '/usr/local/lib/python3.5/dist-packages/numpy/__pycache__/version.cpython-35.pyc'
import 'numpy.version' # <_frozen_importlib_external.SourceFileLoader object at 0xf62bc750>
# /usr/local/lib/python3.5/dist-packages/numpy/__pycache__/_import_tools.cpython-35.pyc matches /usr/local/lib/python3.5/dist-packages/numpy/_import_tools.py
# code object from '/usr/local/lib/python3.5/dist-packages/numpy/__pycache__/_import_tools.cpython-35.pyc'
import 'numpy._import_tools' # <_frozen_importlib_external.SourceFileLoader object at 0xf62bc7b0>
# /usr/local/lib/python3.5/dist-packages/numpy/__pycache__/add_newdocs.cpython-35.pyc matches /usr/local/lib/python3.5/dist-packages/numpy/add_newdocs.py
# code object from '/usr/local/lib/python3.5/dist-packages/numpy/__pycache__/add_newdocs.cpython-35.pyc'
# /usr/local/lib/python3.5/dist-packages/numpy/lib/__pycache__/__init__.cpython-35.pyc matches /usr/local/lib/python3.5/dist-packages/numpy/lib/__init__.py
# code object from '/usr/local/lib/python3.5/dist-packages/numpy/lib/__pycache__/__init__.cpython-35.pyc'
import 'math' # <class '_frozen_importlib.BuiltinImporter'>
# /usr/local/lib/python3.5/dist-packages/numpy/lib/__pycache__/info.cpython-35.pyc matches /usr/local/lib/python3.5/dist-packages/numpy/lib/info.py
# code object from '/usr/local/lib/python3.5/dist-packages/numpy/lib/__pycache__/info.cpython-35.pyc'
import 'numpy.lib.info' # <_frozen_importlib_external.SourceFileLoader object at 0xf61bf110>
# /usr/local/lib/python3.5/dist-packages/numpy/lib/__pycache__/type_check.cpython-35.pyc matches /usr/local/lib/python3.5/dist-packages/numpy/lib/type_check.py
# code object from '/usr/local/lib/python3.5/dist-packages/numpy/lib/__pycache__/type_check.cpython-35.pyc'
# /usr/local/lib/python3.5/dist-packages/numpy/core/__pycache__/__init__.cpython-35.pyc matches /usr/local/lib/python3.5/dist-packages/numpy/core/__init__.py
# code object from '/usr/local/lib/python3.5/dist-packages/numpy/core/__pycache__/__init__.cpython-35.pyc'
# /usr/local/lib/python3.5/dist-packages/numpy/core/__pycache__/info.cpython-35.pyc matches /usr/local/lib/python3.5/dist-packages/numpy/core/info.py
# code object from '/usr/local/lib/python3.5/dist-packages/numpy/core/__pycache__/info.cpython-35.pyc'
import 'numpy.core.info' # <_frozen_importlib_external.SourceFileLoader object at 0xf61bffd0>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/numpy/core/__init__.py", line 16, in <module>
    from . import multiarray
  File "<frozen importlib._bootstrap>", line 1016, in _handle_fromlist
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 666, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 577, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 914, in create_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
ImportError: libf77blas.so.3: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/usr/local/lib/python3.5/dist-packages/numpy/__init__.py", line 142, in <module>
    from . import add_newdocs
  File "<frozen importlib._bootstrap>", line 1016, in _handle_fromlist
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/usr/local/lib/python3.5/dist-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/usr/local/lib/python3.5/dist-packages/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/usr/local/lib/python3.5/dist-packages/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 944, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/usr/local/lib/python3.5/dist-packages/numpy/core/__init__.py", line 26, in <module>
    raise ImportError(msg)
ImportError:
Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
If you're working with a numpy git repo, try `git clean -xdf` (removes all
files not under version control).  Otherwise reinstall numpy.

Original error was: libf77blas.so.3: cannot open shared object file: No such file or directory
```

**Comment by tjguk** [comment]
Ok -- the obvious inference is that the (right) BLAS library isn't installed. I'm not a numpy guy so I don't know what the normal build process is, but it's presumably either a missing binary dependency or a misconfigured build.

**Comment by bennuttall** [comment]
Ah - that makes sense, thanks @tjguk. So should be:

```
sudo apt install libblas-dev
```

I believe?

**Comment by tjguk** [comment]
This isn't my area, but searching seems to suggest: libatlas-base-dev

**Comment by jasongwartz** [comment]
@tjguk nice, that fixes it in the raspbian image. still doesn't work in the default python:3.5 image, but this is a solid fix for me for now.

The following now works inside the `resin/rpi-raspbian` image on a Pi:
```
$ apt update && apt install libatlas-base-dev python3-pip
$ pip3 install numpy -i https://www.piwheels.hostedpi.com/simple
$ python3 -c 'import numpy; print(numpy.zeros(5))'
```

**Comment by tjguk** [comment]
Thanks for confirming @jasongwartz

**Comment by waveform80** [comment]
Just a side note: pip can only deal with Python dependencies, but there's plenty of packages that require external bits (like numpy requiring BLAS). If you need to look up the build dependencies piwheels currently uses, check out the [`deploy_slave.sh`](https://github.com/bennuttall/piwheels/blob/master/deploy_slave.sh) script in the root. You can ignore most of the `python-*` packages in there (because pip should handle those sorts of dependencies), but anything that starts `lib*` is probably worth checking out.

**Comment by DrGFreeman** [comment]
For info, I ran into the same error message after having installed numpy in a virtual enviromnent where global site packages are enabled. I installed numpy with `pip install numpy --ignore-installed`.

As per above comments, I installed libatlas-base-dev (`sudo apt get install libatlas-base-dev`) and I can now import numpy without issue.

**Comment by waveform80** [comment]
@bennuttall looks like we may need to make the associated FAQ a bit more prominent, or maybe add some new ones with specific errors? Something like "I get an ImportError with a package installed from piwheels"? Probably worth tying into whatever we do for #59.

**Comment by bennuttall** [comment]
Sure

**Comment by mskwon** [comment]
A note for people using Alpine, where there is no `libatlas-base-dev`:

As of writing, the latest Alpine (3.10) has numpy packaged for Python 3 on its repo. You can get it with:
`apk update && apk upgrade
apk add --no-cache py3-numpy`

The packaged numpy imports fine on Docker running on a Raspberry Pi 1B.

I wouldn't use a Python image, but rather go with an Alpine image as the packaged numpy is for the packaged Python. 

pandas is also packaged, but it's on the Edge repository in testing:
`apk add --no-cache py3-pandas --repository=http://dl-cdn.alpinelinux.org/alpine/edge/testing`

Though perhaps by the time you read this, it has moved onto the main repository for whatever the latest version of Alpine is.
