### ISSUE TITLE
QT for Python (PySide2) - Does not install

### ISSUE THREAD

**Issue by renansoaress** [bennuttall/piwheels#84]
https://www.piwheels.org/simple/PySide2/ Is empty.

At some time was released an official version of **QT for python (_PySide2_)**, but I find nowhere a way to install on raspberry, strange is that demo game https://www.piwheels.org/simple/Tetris2000-PySide2 / it is available in the pywheels, but when it arrives at the PySide2 installation the process is stopped.
I would like the help of you to make available in PyWheels PySide2 would be of great use to the community I am sure!
**Thank you.**
Sorry for English by Google Translator.

**Comment by bennuttall** [comment]
If you look at Pyside2 on PyPI you will see some wheels are available for other platforms. Usually, a source distribution is provided (e.g. `tar.gz`) but none has been provided here. The way piwheels works is we build wheels from source, but if none is provided we have nothing to build.

The only solution is if the maintainers upload a source distribution or send me a wheel they have built on a Pi.

**Comment by me21** [comment]
There is an explanation of PySide2 build process for Linux at https://wiki.qt.io/Qt_for_Python/GettingStarted/X11.
Won't it help?

**Comment by me21** [comment]
Which step fails?

**Comment by davidwachs** [comment]
Hi All, 
I too am interested in this wheel.  I wish I could assist here but all i can really do is beg and grovel!  Anybody working on this?

Thanks

**Comment by bennuttall** [comment]
If you can try the instructions in the link above, and report back, that would be helpful

**Comment by davidwachs** [comment]
Unfortunately the instructions don't really apply.  It first needs libclang.  By googling around I was able to get that installed.  Then it needs QT 5.11 (needed for pyside2).  I have not been able to get this to compile with OpenGL support so the process stops there.

**Comment by jrast** [comment]
Has anyone made another attempt at this?

**Comment by bennuttall** [comment]
The instructions above suggest:

```bash
git clone https://code.qt.io/pyside/pyside-setup
cd pyside-setup
git branch --track 5.12 origin/5.12
git checkout 5.12
python setup.py install <args>
```

I tried `pip3 wheel .` on a Stretch Pi (as it requires Python 3.5+) and got:

```
root@piwheels5:~/pyside-setup# pip3 wheel . --no-deps
Processing /root/pyside-setup
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    NameError: name 'egg_info' is not defined
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-rt0gm1xl/setup.py", line 289, in <module>
        setup_runner.run_setup()
      File "/tmp/pip-req-build-rt0gm1xl/build_scripts/setup_runner.py", line 157, in run_setup
        raise RuntimeError(msg)
    RuntimeError:
    setup.py invocation failed with exit code: 1.


    setup.py invocation was: /usr/bin/python3 -c egg_info --egg-base pip-egg-info --internal-build-type=shiboken2


    Running process: /usr/bin/python3 -c egg_info --egg-base pip-egg-info --internal-build-type=shiboken2


    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-req-build-rt0gm1xl/
```

**Comment by schlamar** [comment]
Maybe out of date setuptools?! Have you tried `pip install -U setuptools`.

**Comment by asaezper** [comment]
Hi everyone,

I manage to compile PySide2 / QtForPython for RPi3. I used a docker with QEMU inside a raspi, because compilation takes a while and it puts raspberry's CPUs to theirs limits.

Dependencies ar in the Dockfile: https://github.com/asaezper/qt-for-python-rpi3-docker/blob/master/Dockerfile 

And mandatory steps are here: https://github.com/asaezper/qt-for-python-rpi3-docker/blob/master/Dockerfile 

I compile Qt for RPi3 with "normal" VC support. But it's also possible to compile it for RPi3 with experimental graphics, RPi2, etc.

I hope it helps you!

**Comment by bennuttall** [comment]
Cool. Do the wheels work with system python?

**Comment by davidwachs** [comment]
Wow! Thank you!  I’ll have to try it!

**Comment by asaezper** [comment]
> Cool. Do the wheels work with system python?

Yes, I have tested my wheels with system python 3.5. As PySide2 compile against The Python Stable API, it should work also with 3.6 and 3.7. 

On the other hand, we can try to generate a wheel with system Python 2.7. Probably the process will be more or less the same.

**Comment by bennuttall** [comment]
Yes - I meant `python3` in Stretch :+1:
